# Generated by Django 2.1.2 on 2019-01-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='d3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d3_image', models.ImageField(upload_to='images/')),
                ('d3_summary', models.CharField(max_length=200)),
                ('d3_URL', models.CharField(max_length=50)),
            ],
        ),
    ]
