# Generated by Django 2.1.2 on 2019-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='images/')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_post', models.CharField(max_length=1000)),
            ],
        ),
    ]
