# Generated by Django 2.1.2 on 2019-01-27 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_post',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
