# Generated by Django 2.1.2 on 2019-01-27 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190127_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 15, 44, 50, 105806, tzinfo=utc)),
        ),
    ]
