# Generated by Django 2.1.2 on 2019-01-29 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190127_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 15, 35, 18, 595097, tzinfo=utc)),
        ),
    ]
