# Generated by Django 2.1.2 on 2019-01-29 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190129_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 15, 46, 57, 326126, tzinfo=utc)),
        ),
    ]
